name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: run integration test
      run: |
        echo running docker driver intergration test on ubuntu
        env TEST_ARGS="-minikube-start-args=--vm-driver=docker" make integration
